"""empty message

Revision ID: ee50b479c08c
Revises: e37947d00834
Create Date: 2022-11-08 15:26:18.970065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee50b479c08c'
down_revision = 'e37947d00834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['id'])
    op.drop_column('task', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'id')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
